export type HatsOptionCard = {
  title: string;
  description: string;
  image: string;
  imagePosition?: string;
  imageScaleClass?: string;
  details: string[];
  href?: string;
  openInNewTab?: boolean;
};

export const fabricOptions: HatsOptionCard[] = [
  {
    title: "Cotton Twill",
    description: "Primary cotton twill swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-cotton-twill-primary.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-cotton-twill-primary.pdf",
    openInNewTab: true,
  },
  {
    title: "Cotton Canvas",
    description: "Cotton canvas 12oz swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-cotton-canvas-12oz.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-cotton-canvas-12oz.pdf",
    openInNewTab: true,
  },
  {
    title: "Thick Whale Corduroy",
    description: "Thick wale corduroy swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-thick-whale-corduroy.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-thick-whale-corduroy.pdf",
    openInNewTab: true,
  },
  {
    title: "Thin Whale Corduroy",
    description: "Thin wale corduroy swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-thin-whale-corduroy.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-thin-whale-corduroy.pdf",
    openInNewTab: true,
  },
  {
    title: "Cotton Twill Rip Stop",
    description: "Rip stop swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-rip-stop.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-rip-stop.pdf",
    openInNewTab: true,
  },
  {
    title: "Cotton Canvas Poly Blend",
    description: "Canvas cotton poly blend swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-cotton-canvas-poly-blend.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-cotton-canvas-poly-blend.pdf",
    openInNewTab: true,
  },
  {
    title: "Cotton Canvas Rip Stop",
    description: "Cotton canvas rip stop swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-rip-stop-cotton-canvas.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-rip-stop-cotton-canvas.pdf",
    openInNewTab: true,
  },
  {
    title: "Denim",
    description: "Denim swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-denim.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-denim.pdf",
    openInNewTab: true,
  },
  {
    title: "Classic Camo Cotton",
    description: "Classic camo cotton twill swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-classic-camo-cotton.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-classic-camo-cotton.pdf",
    openInNewTab: true,
  },
  {
    title: "Forest Camo Cotton",
    description: "Forest camo cotton twill swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-forest-camo-cotton.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-forest-camo-cotton.pdf",
    openInNewTab: true,
  },
  {
    title: "Heavy Forest Camo Cotton",
    description: "Heavy forest camo cotton twill swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-heavy-forest-camo-cotton.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-heavy-forest-camo-cotton.pdf",
    openInNewTab: true,
  },
  {
    title: "Coarse Hemp",
    description: "Coarse hemp swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-coarse-hemp.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-coarse-hemp.pdf",
    openInNewTab: true,
  },
  {
    title: "Performance Polyester",
    description: "Performance polyester swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-performance-poly.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-performance-poly.pdf",
    openInNewTab: true,
  },
  {
    title: "Printed Polyester",
    description: "Printed polyester swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-printed-polyester.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-printed-polyester.pdf",
    openInNewTab: true,
  },
  {
    title: "Ramie Cotton Blend",
    description: "Ramie cotton blend swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-ramie-cotton-blend.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-ramie-cotton-blend.pdf",
    openInNewTab: true,
  },
  {
    title: "Nylon Rip Stop",
    description: "Nylon rip stop swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-rip-stop-nylon.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-rip-stop-nylon.pdf",
    openInNewTab: true,
  },
  {
    title: "Faux Suede",
    description: "Faux suede swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-faux-suede.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-faux-suede.pdf",
    openInNewTab: true,
  },
  {
    title: "Trucker Mesh",
    description: "Trucker mesh swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-trucker-mesh.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-trucker-mesh.pdf",
    openInNewTab: true,
  },
  {
    title: "Polyester Hat Ropes",
    description: "Polyester hat ropes swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-hat-ropes-polyester.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-hat-ropes-polyester.pdf",
    openInNewTab: true,
  },
  {
    title: "Patterned Hat Ropes",
    description: "Patterned hat ropes swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-patterned-ropes.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-patterned-ropes.pdf",
    openInNewTab: true,
  },
  {
    title: "Polyester Thin Hat Ropes",
    description: "Thin polyester hat ropes swatch deck.",
    image: "/images/gallery/fabric-catalogs/orangegoods-swatch-thin-ropes-polyester.jpg",
    imagePosition: "center top",
    details: [],
    href: "/pdfs/orangegoods-swatch-thin-ropes-polyester.pdf",
    openInNewTab: true,
  },
];

export const decorationOptions: HatsOptionCard[] = [
  {
    title: "3D embroidery",
    description: "Raised front embroidery.",
    image: "/images/gallery/headwear-3d-embroidery-img-7544.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Flat embroidery",
    description: "Clean stitched logo work.",
    image: "/images/gallery/headwear-flat-embroidery-mg-6827.jpg",
    imagePosition: "center 66%",
    details: [],
  },
  {
    title: "Patch",
    description: "Classic patch application.",
    image: "/images/gallery/headwear-patch-mg-6923.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Woven label",
    description: "Low-profile woven branding.",
    image: "/images/gallery/headwear-woven-label-mg-6885.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Screen print",
    description: "Best for printed hits.",
    image: "/images/gallery/hat-feb-img_7544.jpg",
    imagePosition: "center 48%",
    details: [],
  },
  {
    title: "Puff print",
    description: "Raised print with extra depth.",
    image: "/images/gallery/headwear-puff-print-img-7549.jpg",
    imagePosition: "center 51%",
    details: [],
  },
  {
    title: "Heat transfer",
    description: "Smooth applied decoration.",
    image: "/images/gallery/hat-feb-img_7533.jpg",
    imagePosition: "center 54%",
    details: [],
  },
  {
    title: "DTF",
    description: "Full-color transfer option.",
    image: "/images/gallery/headwear-dtf-mg-6778.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Chain stitch",
    description: "Texture with movement.",
    image: "/images/gallery/headwear-chain-stitch-img-7552.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Leather patch",
    description: "Premium patch finish.",
    image: "/images/gallery/headwear-patch-layout-mg-9412.jpg",
    imagePosition: "center 43%",
    details: [],
  },
  {
    title: "Felt patch",
    description: "Soft texture and depth.",
    image: "/images/gallery/headwear-felt-patch-dscf7913.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Printed patch",
    description: "Color-rich patch option.",
    image: "/images/gallery/hat-feb-img_7534.jpg",
    imagePosition: "center 48%",
    details: [],
  },
  {
    title: "Chenille patch",
    description: "More texture, more character.",
    image: "/images/gallery/hat-feb-img_7552.jpg",
    imagePosition: "center 46%",
    details: [],
  },
  {
    title: "PVC rubber patch",
    description: "Durable molded patch detail.",
    image: "/images/gallery/hat-og-patch-studio.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Embroidered patch",
    description: "A stitched patch classic.",
    image: "/images/gallery/patches-og-oval-quality-logo-dscf2869.jpg",
    imagePosition: "center 48%",
    details: [],
  },
  {
    title: "Woven patch",
    description: "Tighter detail, flatter finish.",
    image: "/images/gallery/headwear-woven-patch-mg-6859.jpg",
    imagePosition: "center 52%",
    details: [],
  },
];

export const addOnOptions: HatsOptionCard[] = [
  {
    title: "Interior taping",
    description: "Branded interior tape for a more finished inside hit.",
    image: "/images/gallery/headwear-seam-tape-img-7639.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Back embroidery",
    description: "Add another logo hit on the back.",
    image: "/images/gallery/headwear-back-embroidery-mg-6901-zoom.jpg",
    imagePosition: "center 52%",
    imageScaleClass: "scale-[1.18] group-hover:scale-[1.21]",
    details: [],
  },
  {
    title: "Side embroidery",
    description: "Clean side hits for extra brand presence.",
    image: "/images/gallery/headwear-side-embroidery-img-7667-exposure.jpg",
    imagePosition: "58% 44%",
    details: [],
  },
  {
    title: "Brim rope",
    description: "Add rope across the brim for a more styled finish.",
    image: "/images/gallery/custom-uploaded/headwear-brim-rope-img-7595.jpg",
    imagePosition: "center 58%",
    imageScaleClass: "scale-[1.12] group-hover:scale-[1.15]",
    details: [],
  },
  {
    title: "Closure label",
    description: "A small branded label at the closure.",
    image: "/images/gallery/headwear-closure-label-mg-6920.jpg",
    imagePosition: "center 62%",
    imageScaleClass: "scale-[1.18] group-hover:scale-[1.21]",
    details: [],
  },
  {
    title: "Contrast fabric",
    description: "Mix fabrics or colors for more visual depth.",
    image: "/images/gallery/custom-uploaded/headwear-contrast-fabric-img-7633.jpg",
    imagePosition: "center 54%",
    imageScaleClass: "scale-[1.02] group-hover:scale-[1.05]",
    details: [],
  },
  {
    title: "Stripe trim",
    description: "Decorative trim tape wrapped around the back panels.",
    image: "/images/gallery/headwear-stripe-trim-img-7709.jpg",
    imagePosition: "56% 60%",
    imageScaleClass: "scale-[1.17] group-hover:scale-[1.2]",
    details: [],
  },
  {
    title: "Brim embroidery",
    description: "Add embroidery on the brim for another custom hit.",
    image: "/images/gallery/headwear-brim-embroidery-img-7704.jpg",
    imagePosition: "62% 64%",
    imageScaleClass: "scale-[1.18] group-hover:scale-[1.21]",
    details: [],
  },
];

export const closureOptions: HatsOptionCard[] = [
  {
    title: "Snapback",
    description: "Classic plastic snap for truckers and structured caps.",
    image: "/images/hats/closures/closure-snapback.jpg",
    imagePosition: "center 74%",
    details: [],
  },
  {
    title: "Strapback with clasp",
    description: "Classic strapback adjustability with clasp hardware and a more premium feel.",
    image: "/images/hats/closures/closure-strapback-clasp.jpg",
    imagePosition: "center 68%",
    details: [],
  },
  {
    title: "Velcro closure",
    description: "Easy hook-and-loop adjustability with a softer casual feel.",
    image: "/images/hats/closures/closure-velcro.jpg",
    imagePosition: "center 76%",
    details: [],
  },
  {
    title: "Buckle closure",
    description: "A technical buckle adjuster for nylon and performance styles.",
    image: "/images/hats/closures/closure-clip-buckle.jpg",
    imagePosition: "center 60%",
    details: [],
  },
  {
    title: "Strapback with slider",
    description: "A cleaner strapback adjuster with easy slide hardware.",
    image: "/images/hats/closures/closure-strapback-slider.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Leather clasp",
    description: "A leather strap with clasp hardware for a more elevated finish.",
    image: "/images/hats/closures/closure-leather-clasp.jpg",
    imagePosition: "center 60%",
    details: [],
  },
  {
    title: "Fitted back",
    description: "No adjuster for cleaner bucket and specialty shapes.",
    image: "/images/product/hats/as-colour/1175-bucket-hat-black-back.jpg",
    imagePosition: "center 52%",
    details: [],
  },
];
