export type HatsOptionCard = {
  title: string;
  description: string;
  image: string;
  imagePosition?: string;
  imageScaleClass?: string;
  details: string[];
  href?: string;
  openInNewTab?: boolean;
};

const fabricDeckHref = "/pdfs/hat-fabric-swatch-catalog.pdf";

export const fabricOptions: HatsOptionCard[] = [
  {
    title: "Cotton twill",
    description: "Classic everyday hat fabric.",
    image: "/images/gallery/fabric-closeups/fabric-folds-unsplash.jpg",
    imagePosition: "center 56%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Cotton canvas",
    description: "A little sturdier with more texture.",
    image: "/images/gallery/fabric-closeups/fabric-folds-unsplash.jpg",
    imagePosition: "center 54%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Corduroy Thin Whale",
    description: "Fine wale texture with a softer finish.",
    image: "/images/gallery/fabric-closeups/fabric-ribbed-unsplash.jpg",
    imagePosition: "center 52%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Corduroy Thick Whale",
    description: "Bolder texture with more depth.",
    image: "/images/gallery/fabric-closeups/fabric-ribbed-unsplash.jpg",
    imagePosition: "center 52%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Recycled fabric",
    description: "A cleaner fabric story for the build.",
    image: "/images/gallery/fabric-closeups/fabric-folds-unsplash.jpg",
    imagePosition: "center 56%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Denim",
    description: "Lived-in texture with character.",
    image: "/images/gallery/fabric-closeups/fabric-blue-grid-unsplash.jpg",
    imagePosition: "center 52%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Hemp",
    description: "Dry handfeel with a natural look.",
    image: "/images/gallery/fabric-closeups/fabric-folds-unsplash.jpg",
    imagePosition: "center 54%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Polyester",
    description: "Lighter and more technical.",
    image: "/images/gallery/fabric-closeups/fabric-blue-grid-unsplash.jpg",
    imagePosition: "center 50%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Recycled canvas",
    description: "Structured feel with a recycled blend.",
    image: "/images/gallery/fabric-closeups/fabric-folds-unsplash.jpg",
    imagePosition: "center 54%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Ripstop nylon",
    description: "Outdoor-ready with a technical finish.",
    image: "/images/gallery/fabric-closeups/fabric-blue-grid-unsplash.jpg",
    imagePosition: "center 50%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Faux suede",
    description: "Soft brushed texture with a richer feel.",
    image: "/images/gallery/hat-og-patch-studio.jpg",
    imagePosition: "center 50%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Ripstop cotton canvas",
    description: "Heavier cotton with a technical grid.",
    image: "/images/gallery/fabric-closeups/fabric-blue-grid-unsplash.jpg",
    imagePosition: "center 50%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Ripstop cotton",
    description: "Softer than nylon, still durable.",
    image: "/images/gallery/fabric-closeups/fabric-blue-grid-unsplash.jpg",
    imagePosition: "center 50%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
  {
    title: "Camo",
    description: "Patterned fabric with more personality.",
    image: "/images/gallery/hat-og-patch-studio.jpg",
    imagePosition: "center 50%",
    details: [],
    href: fabricDeckHref,
    openInNewTab: true,
  },
];

export const decorationOptions: HatsOptionCard[] = [
  {
    title: "3D embroidery",
    description: "Raised front embroidery.",
    image: "/images/gallery/headwear-3d-embroidery-img-7544.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Flat embroidery",
    description: "Clean stitched logo work.",
    image: "/images/gallery/headwear-flat-embroidery-mg-6827.jpg",
    imagePosition: "center 66%",
    details: [],
  },
  {
    title: "Patch",
    description: "Classic patch application.",
    image: "/images/gallery/headwear-patch-mg-6923.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Woven label",
    description: "Low-profile woven branding.",
    image: "/images/gallery/headwear-woven-label-mg-6885.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Screen print",
    description: "Best for printed hits.",
    image: "/images/gallery/hat-feb-img_7544.jpg",
    imagePosition: "center 48%",
    details: [],
  },
  {
    title: "Puff print",
    description: "Raised print with extra depth.",
    image: "/images/gallery/headwear-puff-print-img-7549.jpg",
    imagePosition: "center 51%",
    details: [],
  },
  {
    title: "Heat transfer",
    description: "Smooth applied decoration.",
    image: "/images/gallery/hat-feb-img_7533.jpg",
    imagePosition: "center 54%",
    details: [],
  },
  {
    title: "DTF",
    description: "Full-color transfer option.",
    image: "/images/gallery/headwear-dtf-mg-6778.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Chain stitch",
    description: "Texture with movement.",
    image: "/images/gallery/headwear-chain-stitch-img-7552.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Leather patch",
    description: "Premium patch finish.",
    image: "/images/gallery/headwear-patch-layout-mg-9412.jpg",
    imagePosition: "center 43%",
    details: [],
  },
  {
    title: "Felt patch",
    description: "Soft texture and depth.",
    image: "/images/gallery/headwear-felt-patch-dscf7913.jpg",
    imagePosition: "center 52%",
    details: [],
  },
  {
    title: "Printed patch",
    description: "Color-rich patch option.",
    image: "/images/gallery/hat-feb-img_7534.jpg",
    imagePosition: "center 48%",
    details: [],
  },
  {
    title: "Chenille patch",
    description: "More texture, more character.",
    image: "/images/gallery/hat-feb-img_7552.jpg",
    imagePosition: "center 46%",
    details: [],
  },
  {
    title: "PVC rubber patch",
    description: "Durable molded patch detail.",
    image: "/images/gallery/hat-og-patch-studio.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Embroidered patch",
    description: "A stitched patch classic.",
    image: "/images/gallery/patches-og-oval-quality-logo-dscf2869.jpg",
    imagePosition: "center 48%",
    details: [],
  },
  {
    title: "Woven patch",
    description: "Tighter detail, flatter finish.",
    image: "/images/gallery/headwear-woven-patch-mg-6859.jpg",
    imagePosition: "center 52%",
    details: [],
  },
];

export const addOnOptions: HatsOptionCard[] = [
  {
    title: "Interior taping",
    description: "Branded interior tape for a more finished inside hit.",
    image: "/images/gallery/headwear-seam-tape-img-7639.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Back embroidery",
    description: "Add another logo hit on the back.",
    image: "/images/gallery/headwear-back-embroidery-mg-6901-zoom.jpg",
    imagePosition: "center 52%",
    imageScaleClass: "scale-[1.18] group-hover:scale-[1.21]",
    details: [],
  },
  {
    title: "Side embroidery",
    description: "Clean side hits for extra brand presence.",
    image: "/images/gallery/headwear-side-embroidery-img-7667-exposure.jpg",
    imagePosition: "58% 44%",
    details: [],
  },
  {
    title: "Brim rope",
    description: "Add rope across the brim for a more styled finish.",
    image: "/images/gallery/custom-uploaded/headwear-brim-rope-img-7595.jpg",
    imagePosition: "center 58%",
    imageScaleClass: "scale-[1.12] group-hover:scale-[1.15]",
    details: [],
  },
  {
    title: "Closure label",
    description: "A small branded label at the closure.",
    image: "/images/gallery/headwear-closure-label-mg-6920.jpg",
    imagePosition: "center 62%",
    imageScaleClass: "scale-[1.18] group-hover:scale-[1.21]",
    details: [],
  },
  {
    title: "Contrast fabric",
    description: "Mix fabrics or colors for more visual depth.",
    image: "/images/gallery/custom-uploaded/headwear-contrast-fabric-img-7633.jpg",
    imagePosition: "center 54%",
    imageScaleClass: "scale-[1.02] group-hover:scale-[1.05]",
    details: [],
  },
  {
    title: "Stripe trim",
    description: "Decorative trim tape wrapped around the back panels.",
    image: "/images/gallery/headwear-stripe-trim-img-7709.jpg",
    imagePosition: "56% 60%",
    imageScaleClass: "scale-[1.17] group-hover:scale-[1.2]",
    details: [],
  },
  {
    title: "Brim embroidery",
    description: "Add embroidery on the brim for another custom hit.",
    image: "/images/gallery/headwear-brim-embroidery-img-7704.jpg",
    imagePosition: "62% 64%",
    imageScaleClass: "scale-[1.18] group-hover:scale-[1.21]",
    details: [],
  },
];

export const closureOptions: HatsOptionCard[] = [
  {
    title: "Snapback",
    description: "Classic plastic snap for truckers and structured caps.",
    image: "/images/hats/closures/closure-snapback.jpg",
    imagePosition: "center 74%",
    details: [],
  },
  {
    title: "Strapback with clasp",
    description: "Classic strapback adjustability with clasp hardware and a more premium feel.",
    image: "/images/hats/closures/closure-strapback-clasp.jpg",
    imagePosition: "center 68%",
    details: [],
  },
  {
    title: "Velcro closure",
    description: "Easy hook-and-loop adjustability with a softer casual feel.",
    image: "/images/hats/closures/closure-velcro.jpg",
    imagePosition: "center 76%",
    details: [],
  },
  {
    title: "Buckle closure",
    description: "A technical buckle adjuster for nylon and performance styles.",
    image: "/images/hats/closures/closure-clip-buckle.jpg",
    imagePosition: "center 60%",
    details: [],
  },
  {
    title: "Strapback with slider",
    description: "A cleaner strapback adjuster with easy slide hardware.",
    image: "/images/hats/closures/closure-strapback-slider.jpg",
    imagePosition: "center 50%",
    details: [],
  },
  {
    title: "Leather clasp",
    description: "A leather strap with clasp hardware for a more elevated finish.",
    image: "/images/hats/closures/closure-leather-clasp.jpg",
    imagePosition: "center 60%",
    details: [],
  },
  {
    title: "Fitted back",
    description: "No adjuster for cleaner bucket and specialty shapes.",
    image: "/images/product/hats/as-colour/1175-bucket-hat-black-back.jpg",
    imagePosition: "center 52%",
    details: [],
  },
];
