export type GalleryItem = {
  src: string;
  client: string;
  product: string;
  category: "hats" | "apparel" | "bags" | "accessories" | "socks" | "drinkware";
};

export const galleryItems: GalleryItem[] = [
  { src: "/images/gallery/hat-og-patch-_mg_3720.jpg", client: "Orange Goods", product: "OG Patch Hat", category: "hats" },
  { src: "/images/gallery/hat-og-patch-_mg_3949.jpg", client: "Orange Goods", product: "OG Patch Hat", category: "hats" },
  { src: "/images/gallery/hat-og-yosemite-dscf4216.jpg", client: "Orange Goods", product: "OG Patch Hat — Yosemite", category: "hats" },
  { src: "/images/gallery/hat-boatsetter-boat.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-boatsetter-car.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-apteka-bucket.jpg", client: "Apteka", product: "Custom Bucket Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7420.jpg", client: "Boatsetter", product: "Nylon Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7440.jpg", client: "Verve Coffee", product: "Canvas Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7461.jpg", client: "Client", product: "Structured Trucker", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7469.jpg", client: "Client", product: "7-Panel Trucker", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7471.jpg", client: "Client", product: "Two-Tone Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7475.jpg", client: "Client", product: "Perforated Cap", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7480.jpg", client: "Client", product: "Highline Structured Cap", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7491.jpg", client: "Client", product: "Highline White Cap", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7500.jpg", client: "Apteka", product: "Corduroy Bucket Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7506.jpg", client: "Client", product: "Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7514.jpg", client: "Ride & Ridden", product: "Patch Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7528.jpg", client: "Client", product: "Custom Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7541.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7558.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7572.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7590.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7609.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7625.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7645.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7663.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7680.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7700.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7720.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/apparel-686-hoodie-front.jpg", client: "686", product: "Custom Hoodie", category: "apparel" },
  { src: "/images/gallery/apparel-686-hoodie-back.jpg", client: "686", product: "Custom Hoodie — Back", category: "apparel" },
  { src: "/images/gallery/apparel-verve-gd-tee.jpg", client: "Verve Coffee", product: "Grateful Dead Collab Tee", category: "apparel" },
  { src: "/images/gallery/apparel-verve-gd-tee-verve_grateful-dead_tshirt_101.jpg", client: "Verve Coffee", product: "Grateful Dead Collab Tee", category: "apparel" },
  { src: "/images/gallery/apparel-gts-synergy.jpg", client: "GT's Living Foods", product: "Custom Tee", category: "apparel" },
  { src: "/images/gallery/bags-boatsetter-dscf3144.jpg", client: "Boatsetter", product: "Canvas Tote", category: "bags" },
  { src: "/images/gallery/bags-boatsetter-dscf3227.jpg", client: "Boatsetter", product: "Canvas Tote — Detail", category: "bags" },
  { src: "/images/gallery/accessories-apteka-towel-267A5255.jpg", client: "Apteka", product: "Custom Beach Towel", category: "accessories" },
  { src: "/images/gallery/accessories-apteka-towel-267A5393.jpg", client: "Apteka", product: "Custom Beach Towel", category: "accessories" },
  { src: "/images/gallery/accessories-boatsetter-towel.jpg", client: "Boatsetter", product: "Custom Beach Towel", category: "accessories" },
  { src: "/images/gallery/socks-beachly.jpg", client: "Beachly", product: "Plush Custom Socks", category: "socks" },
  { src: "/images/gallery/socks-verve-gd-dscf4857.jpg", client: "Verve Coffee", product: "Grateful Dead Collab Socks", category: "socks" },
  { src: "/images/gallery/socks-firestone-_mg_0147.jpg", client: "Firestone Walker", product: "Custom Can Sock", category: "socks" },
  { src: "/images/gallery/socks-firestone-_mg_0175.jpg", client: "Firestone Walker", product: "Custom Can Sock", category: "socks" },
  { src: "/images/gallery/hat-boatsetter-film1.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-boatsetter-film2.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/apparel-bodyglove-tee.jpg", client: "Body Glove", product: "Embroidered Tee", category: "apparel" },
  { src: "/images/gallery/accessories-daybreak1.jpg", client: "Daybreak Coffee", product: "Custom Goods", category: "accessories" },
  { src: "/images/gallery/accessories-daybreak2.jpg", client: "Daybreak Coffee", product: "Custom Goods", category: "accessories" },
  { src: "/images/gallery/drinkware-goodoonya1.jpg", client: "GoodOnya", product: "Bamboo Water Bottle", category: "drinkware" },
  { src: "/images/gallery/drinkware-goodoonya2.jpg", client: "GoodOnya", product: "Bamboo Water Bottle", category: "drinkware" },
];
