export type GalleryItem = {
  src: string;
  client: string;
  product: string;
  category: "hats" | "apparel" | "bags" | "accessories" | "socks" | "drinkware";
};

export const galleryItems: GalleryItem[] = [
  { src: "/images/gallery/hat-og-patch-_mg_3720.jpg", client: "Orange Goods", product: "OG Patch Hat", category: "hats" },
  { src: "/images/gallery/hat-og-patch-_mg_3949.jpg", client: "Orange Goods", product: "OG Patch Hat", category: "hats" },
  { src: "/images/gallery/hat-og-yosemite-dscf4216.jpg", client: "Orange Goods", product: "OG Patch Hat — Yosemite", category: "hats" },
  { src: "/images/gallery/hat-boatsetter-boat.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-boatsetter-car.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-apteka-bucket.jpg", client: "Apteka", product: "Custom Bucket Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7420.jpg", client: "Boatsetter", product: "Nylon Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7440.jpg", client: "Verve Coffee", product: "Canvas Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7461.jpg", client: "Client", product: "Structured Trucker", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7469.jpg", client: "Client", product: "7-Panel Trucker", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7471.jpg", client: "Client", product: "Two-Tone Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7475.jpg", client: "Client", product: "Perforated Cap", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7480.jpg", client: "Client", product: "Highline Structured Cap", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7491.jpg", client: "Client", product: "Highline White Cap", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7500.jpg", client: "Apteka", product: "Corduroy Bucket Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7506.jpg", client: "Client", product: "Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7514.jpg", client: "Ride & Ridden", product: "Patch Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7528.jpg", client: "Client", product: "Custom Snapback", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7541.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7558.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7572.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7590.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7609.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7625.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7645.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7663.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7680.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7700.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/hat-feb-img_7720.jpg", client: "Client", product: "Custom Hat", category: "hats" },
  { src: "/images/gallery/apparel-686-hoodie-front.jpg", client: "686", product: "Custom Hoodie", category: "apparel" },
  { src: "/images/gallery/apparel-686-hoodie-back.jpg", client: "686", product: "Custom Hoodie — Back", category: "apparel" },
  { src: "/images/gallery/apparel-verve-gd-tee.jpg", client: "Verve Coffee", product: "Grateful Dead Collab Tee", category: "apparel" },
  { src: "/images/gallery/apparel-verve-gd-tee-verve_grateful-dead_tshirt_101.jpg", client: "Verve Coffee", product: "Grateful Dead Collab Tee", category: "apparel" },
  { src: "/images/gallery/apparel-gts-synergy.jpg", client: "GT's Living Foods", product: "Custom Tee", category: "apparel" },
  { src: "/images/gallery/bags-boatsetter-dscf3144.jpg", client: "Boatsetter", product: "Canvas Tote", category: "bags" },
  { src: "/images/gallery/bags-boatsetter-dscf3227.jpg", client: "Boatsetter", product: "Canvas Tote — Detail", category: "bags" },
  { src: "/images/gallery/accessories-apteka-towel-267A5255.jpg", client: "Apteka", product: "Custom Beach Towel", category: "accessories" },
  { src: "/images/gallery/accessories-apteka-towel-267A5393.jpg", client: "Apteka", product: "Custom Beach Towel", category: "accessories" },
  { src: "/images/gallery/accessories-boatsetter-towel.jpg", client: "Boatsetter", product: "Custom Beach Towel", category: "accessories" },
  { src: "/images/gallery/socks-beachly.jpg", client: "Beachly", product: "Plush Custom Socks", category: "socks" },
  { src: "/images/gallery/socks-verve-gd-dscf4857.jpg", client: "Verve Coffee", product: "Grateful Dead Collab Socks", category: "socks" },
  { src: "/images/gallery/socks-firestone-_mg_0147.jpg", client: "Firestone Walker", product: "Custom Can Sock", category: "socks" },
  { src: "/images/gallery/socks-firestone-_mg_0175.jpg", client: "Firestone Walker", product: "Custom Can Sock", category: "socks" },
  { src: "/images/gallery/hat-boatsetter-film1.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/hat-boatsetter-film2.jpg", client: "Boatsetter", product: "Custom Trucker Hat", category: "hats" },
  { src: "/images/gallery/apparel-bodyglove-tee.jpg", client: "Body Glove", product: "Embroidered Tee", category: "apparel" },
  { src: "/images/gallery/accessories-daybreak1.jpg", client: "Daybreak Coffee", product: "Custom Goods", category: "accessories" },
  { src: "/images/gallery/accessories-daybreak2.jpg", client: "Daybreak Coffee", product: "Custom Goods", category: "accessories" },
  { src: "/images/gallery/drinkware-goodoonya1.jpg", client: "GoodOnya", product: "Bamboo Water Bottle", category: "drinkware" },
  { src: "/images/gallery/drinkware-goodoonya2.jpg", client: "GoodOnya", product: "Bamboo Water Bottle", category: "drinkware" },
  { src: "/images/gallery/banner-coffee-apron-2026-08-14.jpg", client: "Banner Coffee", product: "Cafe Apron", category: "accessories" },
  { src: "/images/gallery/banner-coffee-tote-2026-08-14.jpg", client: "Banner Coffee", product: "Canvas Tote", category: "bags" },
  { src: "/images/gallery/field-day-coffee-crewneck-2026-08-14.jpg", client: "Field Day Coffee", product: "Embroidered Crewneck", category: "apparel" },
  { src: "/images/gallery/k1-porsche-merch-display-2026-08-14.jpg", client: "K1 x Porsche", product: "Holiday Merch Display", category: "apparel" },
  { src: "/images/gallery/oak-essentials-tray-2026-08-14.jpg", client: "Oak Essentials", product: "Travertine Tray", category: "accessories" },
  { src: "/images/gallery/stanford-medicine-blanket-2026-08-14.jpg", client: "Stanford Medicine", product: "Woven Blanket", category: "accessories" },
  { src: "/images/gallery/stanford-medicine-laptop-sleeve-2026-08-14.jpg", client: "Stanford Medicine", product: "Padded Laptop Sleeve", category: "accessories" },
  { src: "/images/gallery/boatsetter-towel-detail-2026-08-14.jpg", client: "Boatsetter", product: "Beach Towel — Detail", category: "accessories" },
  { src: "/images/gallery/sundream-pouches-2026-08-14.jpg", client: "Sundream", product: "Retail Pouch Set", category: "accessories" },
  { src: "/images/gallery/goodonya-bamboo-bottles-detail-2026-08-14.jpg", client: "GoodOnya", product: "Bamboo Bottle — Detail", category: "drinkware" },
  { src: "/images/gallery/embroidery-esplanade-brand-hat.jpg", client: "Esplanade Brand", product: "Embroidered Hat", category: "hats" },
  { src: "/images/gallery/embroidery-fish-at-sea-beanies.jpg", client: "Fish At Sea", product: "Custom Beanies", category: "hats" },
  { src: "/images/gallery/headwear-full-custom-verve-larrea-hat-038.jpg", client: "Verve Coffee", product: "Full Custom Larrea Hat", category: "hats" },
  { src: "/images/gallery/headwear-verve-roasters-dscf3088.jpg", client: "Verve Coffee", product: "Roasters Cap", category: "hats" },
  { src: "/images/gallery/apparel-verve-gd-tee-verve_grateful-dead_tshirt_040.jpg", client: "Verve Coffee", product: "Graphic Tee — Front Detail", category: "apparel" },
  { src: "/images/gallery/apparel-verve-gd-tee2.jpg", client: "Verve Coffee", product: "Graphic Tee — Print Detail", category: "apparel" },
  { src: "/images/gallery/embroidery-red-bull-jacket.jpg", client: "Red Bull", product: "Active Jacket", category: "apparel" },
  { src: "/images/gallery/embroidery-trace3-jacket.jpg", client: "Trace3", product: "Branded Jacket", category: "apparel" },
  { src: "/images/gallery/embroidery-k1-apparel-embroidery.jpg", client: "K1", product: "Embroidered Apparel", category: "apparel" },
  { src: "/images/gallery/outerwear-high-st-deli-puffer-mg-2257.jpg", client: "High Street Deli", product: "Custom Puffer Jacket", category: "apparel" },
  { src: "/images/gallery/screen-printing-heal-the-bay-sweatshirt-tote-hat.jpg", client: "Heal the Bay", product: "Sweatshirt + Tote Set", category: "apparel" },
  { src: "/images/gallery/screen-printing-sully-co-coyotee-on-model.webp", client: "Sully & Co", product: "Printed Tee", category: "apparel" },
  { src: "/images/gallery/bags-boatsetter-dscf3238.jpg", client: "Boatsetter", product: "Canvas Tote — Lifestyle", category: "bags" },
  { src: "/images/gallery/bags-boatsetter-dscf3239.jpg", client: "Boatsetter", product: "Canvas Tote — Side Detail", category: "bags" },
  { src: "/images/gallery/bags-boatsetter-dscf3249.jpg", client: "Boatsetter", product: "Canvas Tote — Carry Shot", category: "bags" },
  { src: "/images/gallery/screen-printing-field-day-coffee-totes.jpg", client: "Field Day Coffee", product: "Printed Tote", category: "bags" },
  { src: "/images/gallery/houseware-oak-essentials-travertine-tray.jpg", client: "Oak Essentials", product: "Travertine Tray", category: "accessories" },
  { src: "/images/gallery/packaging-stanford-medicine-thinkhealth-craft-1.jpg", client: "Stanford Medicine", product: "ThinkHealth Kit Packaging", category: "accessories" },
  { src: "/images/gallery/accessories-stanford-medicine-laptop-sleeve.jpg", client: "Stanford Medicine", product: "Laptop Sleeve", category: "accessories" },
  { src: "/images/gallery/accessories-royal-wine-bandana-image-1.jpg", client: "Royal Wine Spirits", product: "Printed Bandana", category: "accessories" },
  { src: "/images/gallery/blankets-sundream-jarritos-1013-2.jpg", client: "Sundream", product: "Woven Blanket", category: "accessories" },
  { src: "/images/gallery/drinkware-verve-milk-glass-mug-2026-08-13.jpg", client: "Verve Coffee", product: "Milk Glass Mug", category: "drinkware" },
  { src: "/images/gallery/drinkware-milk-glass-mug-1-2026-08-14.jpg", client: "Layla Bagels", product: "Milk Glass Mugs", category: "drinkware" },
  { src: "/images/gallery/drinkware-high-st-pilsners-2026-08-13.jpg", client: "High Street Deli", product: "Beer Glasses", category: "drinkware" },
  { src: "/images/gallery/drinkware-stanford-tumblers-ai-1020-2026-08-13.jpg", client: "Stanford Medicine", product: "Matte Tumblers", category: "drinkware" },
  { src: "/images/gallery/drinkware-stanford-bamboo-bottles-2026-08-13.jpg", client: "Stanford Medicine", product: "Bamboo Bottles", category: "drinkware" },
  { src: "/images/gallery/drinkware-goodonya-bottles-mg-2294-2026-08-13.jpg", client: "GoodOnya", product: "Bamboo Bottles", category: "drinkware" },
  { src: "/images/gallery/socks-verve-gd.jpg", client: "Verve Coffee", product: "Graphic Socks", category: "socks" },
  { src: "/images/gallery/socks-firestone-_mg_0156.jpg", client: "Firestone Walker", product: "Custom Can Sock", category: "socks" },
];
